### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [9,43] vs. [32,43]

### ISSUE THREAD

**Issue by linzhijianhhh** [UsmannK/TABOR#1]
Dear author, I encountered a problem while executing the code of snooper.py.
  train_badnet.py has been trained and the environment configuration is configured as required.
  Appreciate your help.

![1](https://user-images.githubusercontent.com/43679808/74627370-9fb68900-518d-11ea-8414-62569073e977.png)

**Comment by ZJZAC** [comment]
It may be a problem about the size of your dataset, which is divisible by 32 with a remainder of 9.

**Comment by BT123** [comment]
tabor/snooper.py
194             for idx in trange(ceil(len(x)/32)):
use int function to replace ceil function.
194             for idx in trange(int(len(x)/32)):

**Comment by UsmannK** [comment]
So sorry, I somehow never saw this. I think it is due to your image size, are you using 32x32 images?
