### ISSUE TITLE
About the upsampling and cropping in your code

### ISSUE THREAD

**Issue by SitengKang** [UsmannK/TABOR#3]
Hi, I am wondering why do you have upsampling and cropping for snooper. Is that necessary?

**Comment by UsmannK** [comment]
It certainly seems like the upsampling isn't necessary as it uses a factor of 1, i.e. does nothing. The cropping I'm not entirely sure anymore. I got that part of the code from an earlier work here: https://github.com/bolunwang/backdoor/blob/master/visualizer.py

**Comment by SitengKang** [comment]
Thanks for that information!
